### ISSUE TITLE
Crash: Unpinning note remotely can crash the app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-android#1015]
### Expected

I expect that note pinning will sync immediately from local to remote and vice versa, with no issues.

### Observed

When I unpin a note remotely, it can crash the app.

### Reproduced

1. In the app, open an unpinned note in the note editor.
2. Tap the 3-dot menu and select "Pin."
3. Go back to the note list.
4. On another device (e.g. Simplenote web on a computer) unpin the note, either from the note list or the note info menu.
5. Notice that in the Android app, the note is still pinned in the note list.
6. Open the note in the note editor again.
7. Go back to the note list and notice that the app crashes.

It looks like steps 6-7 may need to happen in quick succession; sometimes the crash doesn't occur, I think when the note editor stays open for a while before returning to the note list. When this occurs, it results in the following crash reported in Sentry:

`RuntimeException: An error occurred while executing doInBackground()`

Make|Model|Android Version|App Version
-|-|-|-
Motorola|moto e5 play|8.1.0|2.6-rc-1

**Comment by theck13** [comment]
I'm unable to reproduce the crash after multiple attempts with various wait times between Step 6 and 7.

I found the following stack trace in Sentry related to the `RuntimeException: An error occurred while executing doInBackground()` report you mentioned.
<details>
<summary>Stack Trace</summary>
<pre>
java.lang.IllegalStateException: Fragment NoteEditorFragment{d7c0cf9 (cff0345c-62ee-4d48-b3a7-759b15da6fca)} not attached to an activity.
    at androidx.fragment.app.Fragment.requireActivity
    at com.automattic.simplenote.NoteEditorFragment.saveNote
    at com.automattic.simplenote.NoteEditorFragment$SaveNoteTask.doInBackground
    at com.automattic.simplenote.NoteEditorFragment$SaveNoteTask.doInBackground
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:354)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
</pre>
</details>
