### ISSUE TITLE
Crash: Can't login with WordPress.com

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/simplenote-android#1102]
Attempting to login with WordPress.com account results in a crash. 

### Expected
App logs in successfully

### Observed
App crashes and then restarts. There isn't an error message specific to the crash, the only thing listed in logcat is this leaked connection error: 

```
2020-07-17 13:08:50.081 8544-8544/com.automattic.simplenote.debug E/ActivityThread: Activity com.automattic.simplenote.SimplenoteAuthenticationActivity has leaked ServiceConnection net.openid.appauth.browser.CustomTabManager$1@a24d770 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.automattic.simplenote.SimplenoteAuthenticationActivity has leaked ServiceConnection net.openid.appauth.browser.CustomTabManager$1@a24d770 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1805)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1677)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1656)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1721)
        at android.app.ContextImpl.bindService(ContextImpl.java:1650)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
        at androidx.browser.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:73)
        at net.openid.appauth.browser.CustomTabManager.bind(CustomTabManager.java:95)
        at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:113)
        at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:91)
        at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:80)
        at com.automattic.simplenote.SimplenoteAuthenticationActivity.onLoginSheetOtherClicked(SimplenoteAuthenticationActivity.java:106)
        at com.simperium.android.LoginBottomSheetDialogFragment$2.onClick(LoginBottomSheetDialogFragment.java:53)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Reproduced
> 1. Uninstall app and do a fresh build and install
> 2. On the login screen tap on "Login" then "Log in with WordPress.com". A browser will open.
> 3. Enter WordPress.com credentials, then click "Approve" to authorize. 
> 4. App will crash and restart
 
<img src="https://user-images.githubusercontent.com/5810477/87822894-8d6d7380-c82f-11ea-881b-194cdcb5e7ea.gif" width="350"/>

***(Optional)*** If you reproduced the bug on a specific device, please replace DEVICE_MAKE, DEVICE_MODEL, ANDROID_VERSION, and APP_VERSION below with the details for that device.  If you reproduced the bug on multiple devices, please add a row for each device.

Make|Model|Android Version|App Version
-|-|-|-
Emulator - Pixel|3 XL|29|2.8-rc-2(?)
Emulator - Pixel|3 XL|28|2.8-rc-2(?)

**Comment by theck13** [comment]
I can't reproduce the crash with a Google Pixel 3 XL (emulator) running API 29 on Simplenote Android 2.8-rc-2.  The browser on the emulator is Google Chrome 74.0.3729.185.  Are you using Chrome or something else?

**Comment by theck13** [comment]
I was just able to reproduce the crash only when I have the **_Don't keep activities_** setting enabled in **_Developer options_**.  Can you confirm that was enabled while you were seeing this crash?  If so, can you try disabling it and seeing if the crash occurs?

**Comment by AmandaRiu** [comment]
@theck13 Ah that's a good catch! I disabled **Don't keep activities** and voila! It all started working again. Closing ticket.
