### ISSUE TITLE
Crash after WP.com login

### ISSUE THREAD

**Issue by 0nko** [Automattic/simplenote-android#1278]
Reproducible on an emulator running Android 8.1.

**To reproduce:**
1. Install the app
2. Tap on Log in
3. Select Login with WordPress.com
4. Enter the credentials
5. After the browser redirection, approve the login on the web
6. Notice the crash

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.automattic.simplenote.debug/com.automattic.simplenote.SimplenoteAuthenticationActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.simperium.android.LoginBottomSheetDialogFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.simperium.android.LoginBottomSheetDialogFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
        at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at com.simperium.android.AuthenticationActivity.onCreate(AuthenticationActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.NoSuchMethodException: <init> []
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getConstructor(Class.java:1725)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:523)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851) 
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85) 
        at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488) 
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288) 
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106) 
        at com.simperium.android.AuthenticationActivity.onCreate(AuthenticationActivity.java:20) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
 ```

**Comment by theck13** [comment]
I can't reproduce this crash with a Pixel 2 API 27 (Android 8.1 Google Play) emulator running Simplenote Android 2.15.0.  Do you have any developer settings like "Don't keep activities" enabled that might change the behavior?

**Comment by 0nko** [comment]
Oh yeah, it seems to only happen with "Don't keep activities" enabled.

**Comment by theck13** [comment]
Thanks for confirmed that.  I'll move this to Groundskeeping since it can only be reproduced with developer options enabled.
