### ISSUE TITLE
Crash loading markdown in NoteEditorFragment

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#444]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadDataWithBaseURL(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at com.automattic.simplenote.NoteEditorFragment.loadMarkdownData(Unknown Source)
       at com.automattic.simplenote.NoteEditorFragment.access$2400(Unknown Source)
       at com.automattic.simplenote.NoteEditorFragment$saveNoteTask.onPostExecute(Unknown Source)
       at com.automattic.simplenote.NoteEditorFragment$saveNoteTask.onPostExecute(Unknown Source)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by nthcircle** [comment]
PR for fix here: https://github.com/Automattic/simplenote-android/pull/453
