### ISSUE TITLE
Crash in NoteEditorFragment

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#488]
Probably just needs an `isAdded()` check?

```
Fatal Exception: java.lang.IllegalStateException: Fragment NoteEditorFragment{b01061e} is not currently in the FragmentManager
       at android.support.v4.app.FragmentManagerImpl.putFragment(Unknown Source)
       at com.automattic.simplenote.NoteEditorActivity.onSaveInstanceState(Unknown Source)
       at android.app.Activity.performSaveInstanceState(Activity.java:1419)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
       at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4542)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3857)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3916)
       at android.app.ActivityThread.-wrap25(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1512)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by maheshgaya** [comment]
What are the steps to reproduce this?

**Comment by roundhill** [comment]
> What are the steps to reproduce this?

No steps I'm afraid, I grabbed this from the play store crash reports.
