### ISSUE TITLE
Checking a checkbox without first activating the keyboard exits to the note list

### ISSUE THREAD

**Issue by davb5** [Automattic/simplenote-android#631]
#### Steps to reproduce
1. Open an existing note with a checkbox list
2. Do not touch the text input area (in order to avoid activating the keyboard) 
3. Tap a checkbox directly (in order to check it) 

#### What I expected

The checkbox becomes checked and the keyboard does not activate. 

#### What happened instead

The screen flashes black, then dark grey-blue (regardless of theme light or dark setting) then returns to the note list. The checkbox is not checked.

#### Simplenote version

1.6.8

#### OS version

Both Android 9.0.0.159 and android 8.0.0.159

**Comment by davb5** [comment]
Hi Dan, thanks for the quick acknowledgement. No crash dialog or prompt to submit a report. Seeing this on an Honor 10 and on a Mediapad M5 8.4. It only occurs if I try to check a box without first tapping elsewhere to bring up the keyboard. If I bring up the keyboard, dismiss it, then try to check the checkbox it works as expected. Not sure if it'll help but I can try watching adb logcat while it and see if anything useful appears. On 31 Jan 2019 16:25, Dan Roundhill <notifications@github.com> wrote:Thanks for the report! Sounds like a crash to me. Do you get the option to send a report? Also, wondering which devices you are seeing this on.

**Comment by roundhill** [comment]
> Not sure if it'll help but I can try watching adb logcat while it and see if anything useful appears.

If you don't mind that'd be great! I would imaging _something_ is getting logged there. I can't reproduce on a Redmi note 5. I do see some crash logs from Hauwei devices in the play store, could be related to this.

Maybe https://github.com/Automattic/simplenote-android/pull/629 will help with this.

**Comment by davb5** [comment]
Looks like it did actually crash but my DNS is blocking Crashlytics (so no prompt for submitting a report). Sorry - my bad.

Here's the output from logcat for that process from the instant I touch the checkbox. The process then terminates and relaunches with a new PID. I've pasted what I think is the relevant portion here. The complete dump is available at https://gist.github.com/davb5/bc4df9529d4f2b785c45524416a87d8d

```
01-31 17:24:27.637 29929 29929 W System.err: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
01-31 17:24:27.637 29929 29929 W System.err: 	at java.lang.String.substring(String.java:2036)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.automattic.simplenote.NoteEditorFragment.newCursorLocation(Unknown Source:21)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.automattic.simplenote.NoteEditorFragment.refreshContent(Unknown Source:20)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.automattic.simplenote.NoteEditorFragment.access$2200(Unknown Source:0)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.automattic.simplenote.NoteEditorFragment$LoadNoteTask.onPostExecute(Unknown Source:28)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.automattic.simplenote.NoteEditorFragment$LoadNoteTask.onPostExecute(Unknown Source:2)
01-31 17:24:27.638 29929 29929 W System.err: 	at android.os.AsyncTask.finish(AsyncTask.java:727)
01-31 17:24:27.638 29929 29929 W System.err: 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
01-31 17:24:27.638 29929 29929 W System.err: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
01-31 17:24:27.638 29929 29929 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:109)
01-31 17:24:27.638 29929 29929 W System.err: 	at android.os.Looper.loop(Looper.java:207)
01-31 17:24:27.638 29929 29929 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7470)
01-31 17:24:27.638 29929 29929 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
01-31 17:24:27.638 29929 29929 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by roundhill** [comment]
Thanks! Can you try this build to see if it fixes the issue?

https://github.com/Automattic/simplenote-android/releases/download/1.6.9-beta/Simplenote-1.6.9-beta.apk

**Comment by davb5** [comment]
That build resolves the issue, thanks a lot!

I did observe that when ticking the checkbox (without previously opening the keyboard) the keyboard will open the disappear very quickly each time a box is checked or unchecked. If the keyboard has been opened and then dismissed, any check or uncheck action will reopen the keyboard and it will stay on screen. Absolutely not a big deal, may just seem a little unpredictable to users.

Thanks again for investigating!

**Comment by 0nko** [comment]
I'm still seeing the crash (Emulator, running Android 9.0), but a different stack trace:
```
2019-02-01 13:10:24.431 9405-9405/com.automattic.simplenote.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.automattic.simplenote.debug, PID: 9405
    java.lang.IndexOutOfBoundsException: setSpan (-2 ... -2) starts before 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:682)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:674)
        at android.text.Selection.setSelection(Selection.java:93)
        at android.text.Selection.setSelection(Selection.java:77)
        at android.text.Selection.setSelection(Selection.java:152)
        at android.widget.EditText.setSelection(EditText.java:136)
        at com.automattic.simplenote.widgets.SimplenoteEditText.insertChecklist(SimplenoteEditText.java:148)
        at com.automattic.simplenote.NoteEditorFragment.insertChecklist(NoteEditorFragment.java:478)
        at com.automattic.simplenote.NoteEditorFragment.onOptionsItemSelected(NoteEditorFragment.java:456)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
