### ISSUE TITLE
[BUG] App crashes when accidentally clicking space/column right after checkbox

### ISSUE THREAD

**Issue by cocobelgica** [Automattic/simplenote-android#638]
#### Steps to reproduce

1. Create checklist
2. Click on the space/column right after the checkbox (requires dexterity). Screenshot below shows the position I'm talking about.
3. App crashes

#### What I expected

Cursor should just appear right on that spot

#### What happened instead

App crashes.

**NOTE:** This only happens if you click on the exact column right after the checkbox which can accidentally occur if you try to toggle the state of the checkbox. If you try to drag the cursor into that position then the app doesn't crash.

#### Simplenote version

v1.6.9

#### OS/Android version

Tested on 7.1.2 only

#### Screenshot/Video

![screenshot](https://i.imgur.com/YU9byL6.png)

**Comment by roundhill** [comment]
Thanks for the report @cocobelgica! I think I was able to reproduce:

```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.widget.EditText.setSelection(EditText.java:96)
        at com.automattic.simplenote.widgets.SimplenoteEditText$1.run(SimplenoteEditText.java:92)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by roundhill** [comment]
Thanks @theck13
